### PR TITLE
Updated Meteor, Prepared for Heroku

### PR DESCRIPTION
**Pull request by goatandsheep**
I don't know if you'll be ok with me removing create-config, but if people are running it on Heroku, it needed to be made for them. Other than that, I still am planning on making:
- ability to apply for login
- ability to change password

btw, there's a link at the bottom of the pages saying made by labsix, which you don't seem to be part of anymore.

### CODE REVIEW

**Comment by goatandsheep** [comment]
@ehzhang can we approve this change when you have time?

**Comment by ehzhang** [comment]
Hi @goatandsheep, thanks for the PR - Sorry that I haven't been able to review this in a very long time. I've been very busy with school and now work.

I think that this looks broadly good, but I will need to do some additional testing, especially since you've included pinned versions for dependencies.

**Comment by goatandsheep** [comment]
@ehzhang I appreciate you maintaining this and trying hard to ensure high standards before changes are accepted. Take your time and let me know if you need help with the testing!

**Comment by anishathalye** [comment]
Given that the original PR was made half a year ago, it might be worth updating dependencies again.

**Pull request closed without merging**
