### PR TITLE
Add Slack Integration for Tickets

### PR DESCRIPTION
**Pull request by andrewjkerr**
See : #20 

## What in the world...

This PR provides the basic Slack integration as described in #20 which:
(1) Allows users to create/cancel/get tickets via Slack
(2) Posts status changes into a "mentor" Slack channel

## Uh, why?

We (the ops team) used this at [Swamphacks 2017](http://2017.swamphacks.com) with reasonable success; a little over 50% of our tickets were created via Slack. We (the mentors) really appreciated having a feed of new tickets come in. It was very easy to discuss them and tag those who could help out with them.

## Oh, ok, well, uh, how do I test this?

You can test this by following the new instructions in the README to set this code up. Then, go ahead and do the following while verifying the incoming webhook works:

1. Create a ticket via Slack (should succeed)
2. Cancel a ticket via Slack (should succeed)
3. Get a ticket via Slack (should fail; no ticket open!)
4. Cancel a ticket via Slack (should fail; no ticket open!)
5. Create a ticket via Slack (should succeed)
6. Claim the ticket via HELPq & test releasing and completing it
7. Create a ticket via HELPq and do (6) again

## Oh snap, this is cool, but I'd love for you to do [x]

Just ask! More than happy to add more functionality if you'd like. This is (notably) missing the ability for (1) users to rate tickets and (2) mentors to manage tickets.

Addressing (1), I couldn't really find a good way to _force_ users to have users rate tickets like HELPq does. Also, I'm not too keen on rating mentors since they're volunteering their time, but that's less of an excuse. :)

Addressing (2), I figured that mentors would be expected to have HELPq open so building them slash commands seemed like kind of a waste.

## Wait, do you even know how to use Meteor?

No. No I do not. If there's any coding standards I'm violating I'm very sorry! I just learned the minimum needed to do this. Just let me know what needs to be changed and I'll be more than happy to do it!

### CODE REVIEW

**Comment by ehzhang** [comment]
@andrewjkerr awesome! Thanks for the PR!

I'm a bit swamped (hah) with work right now - I'll see about reviewing this soon. I'd also be interested in talking a bit further about usability and whether or not adding slack integrations hurt/help the experience.

Do you have any metrics you'd be willing to share? Either those from the dashboard (ex response times) or just general things like number of total mentors/hackers at the event, etc.

I'd also be interested in any pitfalls you noticed during the event - you mention 'reasonable success' - what do you mean by that? What didn't work? What did work? What was the layout of the hackathon logistically? How did mentors communicate with one another?

Sorry if this is a barrage of questions - not a lot of people take the time to follow up afterwards so it's always good to hear how things went, good or bad :)

**Comment by andrewjkerr** [comment]
Hey @ehzhang, just letting you know that I'm planning on gathering some metrics/data/thoughts for you, but it's going to take a little bit of time since I already destroyed the instance everything was running on. I have the logs and the DB, but I just need to figure out what kind of data I want to extract 😅. Hopefully I'll find some free time in the near future to dig a little deeper!

Until there, here are the metrics from the dashboard:
screen shot 2017-01-22 at 12 43 50 pm

Anything regarding a "user" number is probably a little skewed since creating a ticket via Slack _technically_ didn't associate it with a user. However, anything regarding "mentors" should be accurate as all mentors had to manage tickets via HELPq.

As far as metrics around the event, I _think_ there were about 10 mentors (a couple mentors never responded to tickets, but were lurking around trying to help) with ~350 hackers (yikes). The event ran Friday night through Sunday morning and, of course, the most tickets came in on Saturday night/Sunday morning when most mentors were gone. I guess the lesson learned there is to put mentors on a schedule like volunteers, but organizers are already asking a lot from mentors and... yeah, idk. Just a brain dump. :)

Anyway, let me tackle your questions with what I remember off the top of my head, heh.

---

> you mention 'reasonable success' - what do you mean by that?

Well, heh. Last year, I wrote a Slackbot that crashed every few tickets so it was mainly "hey, come over and talk to a mentor _or_ drop a note in the #mentor channel on Slack". HELPq definitely helped with managing kind of the chaos with having very few mentors and so many hackers.

Slack integration also helped because it was a very easy way of being like "hey, can you create a ticket for this with `/ticket create <topic>` so we can track it?" instead of relying on them to go to HELPq and sign up for an account. Pretty much everyone was on the Slack so it was a super simple way to get tickets filed that would have never been filed without Slack.

The webhook for tickets also helped the mentors as we were able to monitor the tickets and be like "^ @someone" if that was their area of expertise. With such few mentors, it was really nice to have a central place where all of the conversation took place that was also showing the status updates to tickets.

> What didn't work? What did work?

Other than the mentor availability mentioned wayyyyy up above, I think Slack really saved our butts as far as making it super simple to submit tickets. Without Slack, HELPq probably wouldn't have worked as well since it's got a somewhat higher bar to entry. Some people didn't want to "give up their Github/Facebook logins" (/shrug) so we just told them to use Slack instead.

As far as other specifics... I mean, everything seemed to go pretty well. The idea of "submitting tickets for mentorship" worked pretty well except for those who didn't know about the system, but, again, /shrug. Um, yeah, that's all I can think of heh.

> What was the layout of the hackathon logistically?

I'm... not sure if you mean like physically? That might be 2am me thinking, but, meh. Physically, we were in the basement of a library [1] that had a _very_ large open space with varying table types as well as group study rooms (~26 of them). We also had the "first" floor (basement != 1st floor apparently), but there weren't really too many people up there as it was also partially open to non-hacking students.

>  How did mentors communicate with one another?

Most of the communication was through Slack. We had a mentor area where a lot of people would come up and ask questions independently of filing tickets, but most of mentor to mentor comms was through Slack.

---

Cool, I think I hit all of your questions. More than happy to expand on anything I talked about above. I'll also (hopefully be able to) pull some more metrics with regards to tickets created via Slack and tickets created via HELPq as well as possibly get more opinions on how well Slack integrated into it.

Thanks for taking the time to look at this PR! 🎉 

---

[1] Sounds dark and dreary, but is actually pretty dope: http://www.alligator.org/news/campus/article_8d671014-2c11-11e4-9d7d-0019bb2963f4.html

**Comment by ehzhang** [comment]
> The event ran Friday night through Sunday morning and, of course, the most tickets came in on Saturday night/Sunday morning when most mentors were gone.

Haha yeah that seems to be a pretty standard thing (http://ehz.io/HELPq-data/)

> I think Slack really saved our butts as far as making it super simple to submit tickets. Without Slack, HELPq probably wouldn't have worked as well since it's got a somewhat higher bar to entry. Some people didn't want to "give up their Github/Facebook logins" (/shrug) so we just told them to use Slack instead.

This makes a lot of sense, and is something that we have run into in the past. I will admit that I'm a bit hesitant to add slack integration though because there is the potential to lose a lot of the key features that rely on the interface - things like rating tickets, knowing how many mentors are online, and knowing when your ticket gets claimed.

At larger hackathons (1000+) where there are lots of mentors (100+), slack unfortunately doesn't scale very well, and I'm afraid that other organizers will opt for slack integration because it's the new hotness and have a worse experience because of it. The way we solve this issue is that we effectively "force" users to sign in - which is of course not the ideal, but hey, we have the power :P Adding slack messages to post to a channel for mentors would also defeat the one core "Pull, don't Push" experience which has helped scale quality mentorship, since we want mentors to be pulling from a queue actively rather than waiting to get pinged. Again, this is something that is more effective at larger hackathons or one centered around mentorship (like Blueprint) where tickets are coming in very frequently.

I asked about the logistical setup (probably should've gone with physical, so kudos to you for guessing what I meant!) because it affects us slightly. For HackMIT and Blueprint, where we've used this extensively, we had rotating projector slides and an arena-style layout that projected the link every few minutes, so hackers were generally very aware. For more "decentralized" hackathons, slack may make a bit more sense for acting as that central 'hub'.

Whew sorry for the wall of text.

What I would like to say is 🎉 thank you 🎉 for the PR and especially for the feedback! Since this stuff is pretty tightly wound into some of the core code I would like to take a bit more time to review/spin up your slackbot as well to get a real sense of how it all works together. I'll follow up with more comments related to that later :)

I think this would be a really useful change and would love to see it get merged. I hope you're not taken aback by my need to vet this thoroughly :P

**Comment by andrewjkerr** [comment]
Hah, walls of texts are fine; I seem to write essays when talking about pull requests. :)

> slack unfortunately doesn't scale very well, and I'm afraid that other organizers will opt for slack integration because it's the new hotness and have a worse experience because of it

Yeaaaaah. That's definitely a downside. But, I think that if the organizers go through the effort to set up Slack to work with HELPq, they'll also have time to think about the downsides and (hopefully) have enough information in order to see if it'll hinder the experience of improve it. In Swamphack's case, I think it improved it. :)

But, anyway, give it a shot and let me know what you think! I definitely appreciate the thoughtful responses and understand the thorough vetting.

Thanks again for making such a dope project! :tada:

**Comment by andrewjkerr** [comment]
This is pretty stale so I'm going to close this out. :)

**Pull request closed without merging**
